export const BRANDS = [
    'Baume & Mercier',
    'Bigli',
    'Blancpain',
    'Breguet',
    'Breitling',
    'BUBEN&ZORWEG',
    'BVLGARI',
    'Cartier',
    'CHANEL',
    'Chantecler',
    'Chopard',
    'dinh van',
    'Ebel',
    'FOPE',
    'FRED',
    'Gemmy Bear',
    'Grand Seiko',
    'Hublot',
    'IWC',
    'Jaeger-LeCoultre',
    'Leanschi',
    'Longines',
    'Love Collection',
    'Marco Bicego',
    'Messika',
    'OMEGA',
    'Panerai',
    'Pasquale Bruni',
    'Patek Philippe',
    'Piaget',
    'Pomellato',
    'Rolex',
    'Roberto Coin',
    'Roger Dubuis',
    'Royal Asscher',
    'Schaap en Citroen',
    'Serafino Consoli',
    'Shamballa',
    'Swiss KubiK',
    'TAG Heuer',
    'Tamara Comolli',
    'Tirisi Productry',
    'Tirisi Moda',
    'TUDOR',
    'Ulysse Nardin',
    'Vacheron Constantin',
    'Yana Nesper',
    'Zenith'
] as const;

export type Brand = typeof BRANDS[number];
